"""initial schema

Revision ID: 79b98888e4fe
Revises: 924d105bab25
Create Date: 2025-12-11 16:14:01.978376

"""

from alembic import op
import sqlalchemy as sa


revision = '79b98888e4fe'
down_revision = '924d105bab25'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager',
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('admin_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager')
    # ### end Alembic commands ###
